# Generated by Django 5.2.13 on 2026-04-16 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AddField(
            model_name='lead',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='descricao',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
