# Generated by Django 5.2.13 on 2026-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options_lead_data_criacao_lead_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='descricao',
            field=models.TextField(default='', max_length=500),
        ),
    ]
